name: Docker Image Build Orchestrator

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: false

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: build-nvidia-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            tag: 'flagcx-nvidia'
            label: 'latest'
            runson: 'h20'
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-nvidia
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_NVIDIA
          
          # for now metax base image can't official access without a token.
          # use h20 instance just for build image.
          - job_name: build-metax-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            tag: 'flagcx-metax'
            label: 'latest'
            runson: 'h20'
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-metax
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_METAX
    
    uses: flagos-ai/build-infra/.github/workflows/imagebuild.yml@main
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      tag: ${{ matrix.tag }}
      label: ${{ matrix.label }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagcx'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
